<?php

return [
    'catalog' => [
        'modules' => [
            'modulo.combustible.view',
            'modulo.documentacion.view',
            'modulo.configuracion.view',
        ],

        'pages' => [
            'pagina.mis-vehiculos.view',
            'pagina.fondeo-operativo.view',
            'pagina.fondeo-financiero.view',
            'pagina.carga-extemporanea.view',
            'pagina.reporte-combustible.view',
            'pagina.reporte-documentos.view',
        ],

        'resources' => [
            'carga-combustible',
            'solicitud-carga-combustible',
            'tarjeta-combustible',
            'tarjeta-saldo-movimiento',
            'fondeo',
            'vehiculo-fondeo-config',
            'vehiculo',
            'vehiculo-documento',
            'alerta-documento',
            'alerta-rendimiento',
            'centro-costo',
            'cuenta-concentradora',
            'departamento',
            'localidad',
            'marca-vehiculo',
            'tipo-documento',
            'tipo-vehiculo',
            'vehiculo-estatus',
            'vehiculo-localidad',
            'vehiculo-departamento',
            'vehiculo-cuenta-analitica',
            'vehiculo-tarjeta',
            'vehiculo-responsable',
            'vehiculo-chofer',
            'usuario',
            'rol',
            'aseguradora',
            'poliza-seguro',
            'tipo-pago',
        ],

        'operations' => [
            'carga-combustible.create-extemporanea',
            'carga-combustible.update-own-assignment',
            'alerta-documento.update-own',
            'alerta-rendimiento.update-own',
            'fondeo-financiero.fondear',
            'fondeo-financiero.retirar',
            'fondeo-financiero.transferir',
            'reporte-combustible.export',
            'reporte-documentos.export',
        ],
    ],

    'roles' => [
        'admin' => '*',

        'activos' => [
            'modulo.combustible.view',
            'modulo.documentacion.view',
            'modulo.configuracion.view',
            'pagina.fondeo-financiero.view',
            'pagina.reporte-combustible.view',
            'pagina.reporte-documentos.view',
            'carga-combustible.view',
            'carga-combustible.create',
            'tarjeta-saldo-movimiento.view',
            'vehiculo-fondeo-config.view',
            'vehiculo-fondeo-config.create',
            'vehiculo-fondeo-config.update',
            'vehiculo.view',
            'vehiculo.create',
            'vehiculo.update',
            'centro-costo.view',
            'centro-costo.create',
            'centro-costo.update',
            'cuenta-concentradora.view',
            'cuenta-concentradora.create',
            'cuenta-concentradora.update',
            'departamento.view',
            'localidad.view',
            'localidad.create',
            'localidad.update',
            'marca-vehiculo.view',
            'marca-vehiculo.create',
            'marca-vehiculo.update',
            'tipo-documento.view',
            'tipo-documento.create',
            'tipo-documento.update',
            'tipo-vehiculo.view',
            'tipo-vehiculo.create',
            'tipo-vehiculo.update',
            'vehiculo-estatus.view',
            'vehiculo-estatus.create',
            'vehiculo-estatus.update',
            'vehiculo-localidad.view',
            'vehiculo-localidad.create',
            'vehiculo-localidad.update',
            'vehiculo-departamento.view',
            'vehiculo-cuenta-analitica.view',
            'vehiculo-tarjeta.view',
            'vehiculo-tarjeta.create',
            'vehiculo-tarjeta.update',
            'vehiculo-responsable.view',
            'vehiculo-responsable.create',
            'vehiculo-responsable.update',
            'vehiculo-chofer.view',
            'vehiculo-documento.view',
            'vehiculo-documento.create',
            'vehiculo-documento.update',
            'alerta-documento.view',
            'alerta-documento.update',
            'alerta-rendimiento.view',
            'solicitud-carga-combustible.view',
            'usuario.view',
            'usuario.create',
            'usuario.update',
            'aseguradora.view',
            'aseguradora.create',
            'aseguradora.update',
            'poliza-seguro.view',
            'poliza-seguro.create',
            'poliza-seguro.update',
            'tipo-pago.view',
            'tipo-pago.create',
            'tipo-pago.update',
            'reporte-combustible.export',
            'reporte-documentos.export',
        ],

        'fondeo' => [
            'modulo.combustible.view',
            'pagina.fondeo-operativo.view',
            'pagina.fondeo-financiero.view',
            'tarjeta-combustible.view',
            'tarjeta-saldo-movimiento.view',
            'fondeo.view',
            'fondeo.create',
            'fondeo.update',
            'vehiculo-fondeo-config.view',
            'vehiculo-fondeo-config.create',
            'vehiculo-fondeo-config.update',
            'vehiculo.view',
            'centro-costo.view',
            'cuenta-concentradora.view',
            'fondeo-financiero.fondear',
            'fondeo-financiero.retirar',
            'fondeo-financiero.transferir',
        ],

        'responsable' => [
            'modulo.combustible.view',
            'modulo.documentacion.view',
            'pagina.mis-vehiculos.view',
            'pagina.carga-extemporanea.view',
            'pagina.reporte-combustible.view',
            'pagina.reporte-documentos.view',
            'carga-combustible.view',
            'carga-combustible.create',
            'carga-combustible.update-own-assignment',
            'vehiculo-documento.view',
            'alerta-documento.view',
            'alerta-documento.update-own',
            'alerta-rendimiento.view',
            'alerta-rendimiento.update-own',
            'solicitud-carga-combustible.view',
            'reporte-combustible.export',
            'reporte-documentos.export',
        ],

        'auxiliar_responsable' => [
            'modulo.combustible.view',
            'modulo.documentacion.view',
            'pagina.mis-vehiculos.view',
            'pagina.carga-extemporanea.view',
            'pagina.reporte-combustible.view',
            'pagina.reporte-documentos.view',
            'carga-combustible.view',
            'carga-combustible.create',
            'carga-combustible.update-own-assignment',
            'vehiculo-documento.view',
            'vehiculo-documento.create',
            'vehiculo-documento.update',
            'alerta-documento.view',
            'alerta-documento.update-own',
            'alerta-rendimiento.view',
            'alerta-rendimiento.update-own',
            'solicitud-carga-combustible.view',
            'reporte-combustible.export',
            'reporte-documentos.export',
        ],

        'chofer' => [
            'modulo.combustible.view',
            'pagina.mis-vehiculos.view',
            'carga-combustible.view',
            'carga-combustible.create',
        ],

        'administracion' => [],
    ],
];
